// Auto-generated file - DO NOT EDIT DIRECTLY
// Generated by scripts/generate-prompt-configs.ts
// Edit the markdown files in content/canvas-flow/ instead

import type { AudienceConfig, PriorityConfig } from "@/lib/prompt-config-types";

export const AUDIENCE_CONFIGS: AudienceConfig[] = [
  {
    id: "benefits-committee",
    audience: "Benefits Committee",
    description: "Cross-functional group",
    promptTemplate:
      "You are presenting to a cross-functional Benefits Committee at {{clientName}}.\n\n## Committee Priorities\n- Balance multiple stakeholder perspectives\n- Provide comprehensive view for informed decision-making\n- Address concerns from HR, Finance, and Operations\n- Support consensus-building with clear options\n- Include both strategic and tactical considerations\n\n## Communication Style\n- Present balanced analysis from multiple angles\n- Show how options affect different stakeholder groups\n- Include employee impact alongside financial analysis\n- Provide clear decision criteria and trade-off framework\n- Use visual comparisons to facilitate discussion\n- Address common questions and concerns proactively\n- Include recommended next steps for committee action",
  },
  {
    id: "c-suite",
    audience: "C-Suite Executives",
    description: "CEO, CFO, COO",
    promptTemplate:
      "You are presenting to C-Suite executives (CEO, CFO, COO) at {{clientName}}.\n\n## Executive Priorities\n- Focus on strategic implications and ROI\n- Present high-level financial summaries with clear bottom-line impact\n- Emphasize competitive positioning and enterprise risk management\n- Keep technical details minimal - use business language\n- Highlight decision points requiring executive action\n\n## Communication Style\n- Lead with key takeaways and recommendations\n- Use data visualizations that tell a clear story at a glance\n- Be concise - executive time is limited\n- Connect benefits decisions to broader business outcomes\n- Frame options in terms of strategic trade-offs\n- Include competitive benchmarking context",
  },
  {
    id: "hr-leadership",
    audience: "HR Leadership",
    description: "CHRO, Benefits Manager",
    promptTemplate:
      "You are presenting to HR Leadership (CHRO, Benefits Manager) at {{clientName}}.\n\n## HR Leadership Priorities\n- Balance employee experience with cost management\n- Demonstrate understanding of talent market dynamics\n- Address compliance and administrative considerations\n- Show impact on HR operations and workload\n- Connect benefits to talent acquisition and retention goals\n\n## Communication Style\n- Provide detailed plan comparisons and options analysis\n- Include employee communication considerations\n- Address implementation timeline and change management\n- Highlight wellness and employee engagement opportunities\n- Show how recommendations align with HR strategy\n- Include detailed cost breakdowns by plan and tier",
  },
  {
    id: "finance-team",
    audience: "Finance Team",
    description: "Financial analysis focus",
    promptTemplate:
      "You are presenting to the Finance Team at {{clientName}}.\n\n## Financial Analysis Priorities\n- Provide detailed cost modeling and projections\n- Show multi-year financial impact scenarios\n- Include actuarial data and claims analysis\n- Present budget variance analysis\n- Demonstrate ROI for recommended strategies\n\n## Communication Style\n- Lead with numbers and financial metrics\n- Use detailed tables and data visualizations\n- Show year-over-year comparisons\n- Include sensitivity analysis for key assumptions\n- Present funding alternatives and cash flow implications\n- Provide detailed breakdowns by cost category\n- Include total cost of ownership analysis",
  },
];

export const PRIORITY_CONFIGS: PriorityConfig[] = [
  {
    id: "employee-experience",
    priority: "Employee Experience",
    description: "Member satisfaction",
    promptTemplate:
      "Given the client's focus on employee experience for the {{renewalPeriod}} renewal:\n\n## Employee Experience Focus\n- Evaluate member satisfaction and engagement metrics\n- Analyze ease of use and administrative burden\n- Review communication clarity and enrollment experience\n- Assess wellness program integration and utilization\n- Consider digital tools and member support resources\n\n## Key Deliverables\n- Member feedback analysis and satisfaction trends\n- Administrative process assessment\n- Communication strategy recommendations\n- Wellness program utilization and ROI analysis\n- Digital experience evaluation with improvement opportunities\n- Change management recommendations for any plan changes",
  },
  {
    id: "data-transparency",
    priority: "Data Transparency",
    description: "Better insights and control",
    promptTemplate:
      "Given the client's focus on data transparency for the {{renewalPeriod}} renewal:\n\n## Data & Analytics Focus\n- Review current data access and reporting capabilities\n- Identify opportunities for enhanced analytics\n- Evaluate claims data quality and completeness\n- Assess vendor reporting and performance metrics\n- Analyze utilization patterns and cost drivers in detail\n\n## Key Deliverables\n- Data availability assessment and gap analysis\n- Enhanced reporting recommendations\n- Claims analytics deep-dive with actionable insights\n- Vendor performance scorecard with metrics\n- Utilization analysis identifying optimization opportunities\n- Recommendations for improved data governance and access",
  },
  {
    id: "talent-competitiveness",
    priority: "Talent Competitiveness",
    description: "Market positioning",
    promptTemplate:
      "Given the client's focus on talent competitiveness for the {{renewalPeriod}} renewal:\n\n## Market Positioning Focus\n- Benchmark benefits against industry peers and competitors\n- Analyze total rewards positioning in the talent market\n- Identify differentiating benefits that attract top talent\n- Evaluate emerging benefit trends and innovative offerings\n- Assess geographic and demographic competitiveness\n\n## Key Deliverables\n- Competitive benchmarking analysis vs. industry peers\n- Total rewards comparison showing market position\n- Emerging benefits trends and adoption recommendations\n- Talent attraction and retention impact analysis\n- Recommendations for competitive differentiation\n- Regional market analysis for key hiring locations",
  },
  {
    id: "coverage-quality",
    priority: "Coverage Quality",
    description: "Maintain rich benefits",
    promptTemplate:
      "Given the client's priority on maintaining coverage quality for the {{renewalPeriod}} renewal:\n\n## Coverage Analysis Focus\n- Evaluate current benefit richness against market standards\n- Identify areas where coverage can be preserved or enhanced\n- Analyze network adequacy and provider access\n- Assess prescription drug formulary and specialty coverage\n- Review out-of-pocket maximums and cost-sharing structures\n\n## Key Deliverables\n- Coverage comparison showing current vs. proposed benefits\n- Network analysis with provider access metrics\n- Formulary review highlighting any changes\n- Member impact analysis by coverage category\n- Recommendations for maintaining value while managing costs",
  },
  {
    id: "cost-predictability",
    priority: "Cost Predictability",
    description: "Stable multi-year costs",
    promptTemplate:
      "Given the client's priority on cost predictability for the {{renewalPeriod}} renewal:\n\n## Cost Stability Focus\n- Analyze historical cost volatility and trend patterns\n- Evaluate funding alternatives for better predictability\n- Assess stop-loss and risk management options\n- Model multi-year rate guarantees and their trade-offs\n- Review reserve requirements and cash flow planning\n\n## Key Deliverables\n- Cost trend analysis showing year-over-year volatility\n- Funding alternative comparison (fully-insured vs. self-funded)\n- Stop-loss analysis with attachment point recommendations\n- Multi-year rate lock options with cost-benefit analysis\n- Budget forecasting model with confidence intervals\n- Risk mitigation strategies ranked by effectiveness",
  },
  {
    id: "cost-management",
    priority: "Cost Management",
    description: "Minimize premium increases",
    promptTemplate:
      "Given the client's emphasis on cost management for the {{renewalPeriod}} renewal:\n\n## Cost Analysis Focus\n- Analyze all cost drivers and their relative impact on total spend\n- Identify specific opportunities for premium reduction or containment\n- Compare current costs against benchmarks (expected increase: {{expectedIncrease}}%)\n- Present cost-saving strategies with projected savings by option\n- Model different contribution and plan design scenarios\n\n## Key Deliverables\n- Cost driver breakdown showing largest contributors\n- Savings opportunities ranked by impact and feasibility\n- Contribution strategy alternatives with employee impact\n- Plan design changes that reduce costs without major disruption\n- Multi-year cost projections under different scenarios",
  },
];
