/**
 * Build script to generate TypeScript config from markdown files
 * Run with: bun run scripts/generate-prompt-configs.ts
 */
import fs from "node:fs";
import path from "node:path";
import { loadPromptConfigurations } from "../lib/prompt-config-loader";

const OUTPUT_PATH = path.join(
  process.cwd(),
  "app",
  "canvas-flow",
  "_generated",
  "prompt-configs.ts"
);

function generatePromptConfigs() {
  console.log("Loading prompt configurations from markdown files...");

  const configs = loadPromptConfigurations();

  console.log(`Found ${configs.audiences.length} audience configs`);
  console.log(`Found ${configs.priorities.length} priority configs`);

  const output = `// Auto-generated file - DO NOT EDIT DIRECTLY
// Generated by scripts/generate-prompt-configs.ts
// Edit the markdown files in content/canvas-flow/ instead

import type { AudienceConfig, PriorityConfig } from "@/lib/prompt-config-types";

export const AUDIENCE_CONFIGS: AudienceConfig[] = ${JSON.stringify(configs.audiences, null, 2)};

export const PRIORITY_CONFIGS: PriorityConfig[] = ${JSON.stringify(configs.priorities, null, 2)};
`;

  // Ensure output directory exists
  const outputDir = path.dirname(OUTPUT_PATH);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
    console.log(`Created directory: ${outputDir}`);
  }

  fs.writeFileSync(OUTPUT_PATH, output, "utf-8");
  console.log(`Generated prompt configs at: ${OUTPUT_PATH}`);
}

generatePromptConfigs();
